-fixed max_length 'status' field
django-oscar/django-oscar-paypal pull request #261
Opened 2020-12-03 20:34 UTC by sdpcrewofficial

-row 'status' in express_checkout models should be 9 character to contain the 'COMPLETED' status

2020-12-05 02:52 UTC, solarissmoke requested changes

2020-12-05 02:52 UTC, solarissmoke commented on paypal/express_checkout/models.py
> +    status = models.CharField(max_length=9)
Please generate a migration for this change - this needs to be added to `paypal/migrations`.

2021-02-07 18:46 UTC, woutdp commented
I've hit the same issue and solved it here: https://github.com/django-oscar/django-oscar-paypal/pull/270

Also note that setting it to 255 is a bit more safe since that's what's in the PayPal spec:
https://developer.paypal.com/docs/api/orders/v2#orders-capture-response
![image](https://user-images.githubusercontent.com/3637265/107156185-bbccb080-6931-11eb-82b8-715a1d684325.png)

2021-02-08 03:33 UTC, solarissmoke commented
Closing in favour of #270 which I'll try and review in the course of this week.

2021-02-08 03:33 UTC, closed without merging